repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [ --fix, --unsafe-fixes ]
        files: ^backend/
      - id: ruff-format
        args: [ --line-length=100 ]
        files: ^backend/

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.25
    hooks:
      - id: validate-pyproject
        additional_dependencies: [ "validate-pyproject-schema-store[all]" ]
        files: ^backend/pyproject\.toml$

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.22.1
    hooks:
      - id: markdownlint-cli2
        args:
          - --fix
          - --config
          - backend/pyproject.toml
          - --configPointer
          - /tool/markdownlint-cli2

  - repo: https://github.com/crate-ci/typos
    rev: v1.46.3
    hooks:
      - id: typos

  - repo: local
    hooks:
      - id: lint-frontend
        name: lint front-end directory
        entry: bash -c 'cd frontend && npm run lint'
        language: system
        pass_filenames: false
        always_run: true
