// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetMetaMetaGetData, GetMetaMetaGetResponses, GetModelsModelsGetData, GetModelsModelsGetResponses, HealthCheckHealthGetData, HealthCheckHealthGetResponses, RefreshDataRefreshPostData, RefreshDataRefreshPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health Check
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckHealthGetData, ThrowOnError>): RequestResult<HealthCheckHealthGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthCheckHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Get Meta
 */
export const getMetaMetaGet = <ThrowOnError extends boolean = false>(options?: Options<GetMetaMetaGetData, ThrowOnError>): RequestResult<GetMetaMetaGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetMetaMetaGetResponses, unknown, ThrowOnError>({ url: '/meta', ...options });

/**
 * Refresh Data
 */
export const refreshDataRefreshPost = <ThrowOnError extends boolean = false>(options?: Options<RefreshDataRefreshPostData, ThrowOnError>): RequestResult<RefreshDataRefreshPostResponses, unknown, ThrowOnError> => (options?.client ?? client).post<RefreshDataRefreshPostResponses, unknown, ThrowOnError>({ url: '/refresh', ...options });

/**
 * Get Models
 */
export const getModelsModelsGet = <ThrowOnError extends boolean = false>(options?: Options<GetModelsModelsGetData, ThrowOnError>): RequestResult<GetModelsModelsGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetModelsModelsGetResponses, unknown, ThrowOnError>({ url: '/models', ...options });
