// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * CombinedModel
 */
export type CombinedModel = {
    /**
     * Name
     */
    name?: string;
    /**
     * Creator
     */
    creator?: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Created
     */
    created?: number | null;
    /**
     * Url Openrouter
     */
    url_openrouter?: string | null;
    /**
     * Url Artificialanalysis
     */
    url_artificialanalysis?: string;
    /**
     * Knowledge Cutoff
     */
    knowledge_cutoff?: number | null;
    /**
     * Context Length
     */
    context_length?: number | null;
    /**
     * Input Modalities
     */
    input_modalities: Array<InputModality>;
    /**
     * Output Modalities
     */
    output_modalities: Array<OutputModality>;
    /**
     * Pricing Input
     */
    pricing_input?: number | null;
    /**
     * Pricing Output
     */
    pricing_output?: number | null;
    /**
     * Speed Tokens Per Second
     */
    speed_tokens_per_second?: number | null;
    /**
     * Speed Time To First Token
     */
    speed_time_to_first_token?: number | null;
    /**
     * Speed Time To First Answer Token
     */
    speed_time_to_first_answer_token?: number | null;
    /**
     * Benchmark Aa Artificial Analysis Intelligence Index
     */
    benchmark_aa_artificial_analysis_intelligence_index?: number | null;
    /**
     * Benchmark Aa Artificial Analysis Coding Index
     */
    benchmark_aa_artificial_analysis_coding_index?: number | null;
    /**
     * Benchmark Aa Artificial Analysis Math Index
     */
    benchmark_aa_artificial_analysis_math_index?: number | null;
    /**
     * Benchmark Aa Mmlu Pro
     */
    benchmark_aa_mmlu_pro?: number | null;
    /**
     * Benchmark Aa Gpqa
     */
    benchmark_aa_gpqa?: number | null;
    /**
     * Benchmark Aa Hle
     */
    benchmark_aa_hle?: number | null;
    /**
     * Benchmark Aa Livecodebench
     */
    benchmark_aa_livecodebench?: number | null;
    /**
     * Benchmark Aa Scicode
     */
    benchmark_aa_scicode?: number | null;
    /**
     * Benchmark Aa Math 500
     */
    benchmark_aa_math_500?: number | null;
    /**
     * Benchmark Aa Aime
     */
    benchmark_aa_aime?: number | null;
    /**
     * Benchmark Aa Aime 25
     */
    benchmark_aa_aime_25?: number | null;
    /**
     * Benchmark Aa Ifbench
     */
    benchmark_aa_ifbench?: number | null;
    /**
     * Benchmark Aa Lcr
     */
    benchmark_aa_lcr?: number | null;
    /**
     * Benchmark Aa Terminalbench Hard
     */
    benchmark_aa_terminalbench_hard?: number | null;
    /**
     * Benchmark Aa Tau2
     */
    benchmark_aa_tau2?: number | null;
    /**
     * Benchmark Aa Tau Banking
     */
    benchmark_aa_tau_banking?: number | null;
    /**
     * Benchmark Aa Terminalbench V2 1
     */
    benchmark_aa_terminalbench_v2_1?: number | null;
    /**
     * Benchmark Or Intelligence Index
     */
    benchmark_or_intelligence_index?: number | null;
    /**
     * Benchmark Or Coding Index
     */
    benchmark_or_coding_index?: number | null;
    /**
     * Benchmark Or Agentic Index
     */
    benchmark_or_agentic_index?: number | null;
};

/**
 * InputModality
 *
 * OpenAPI `InputModality`.
 */
export type InputModality = "text" | "image" | "file" | "audio" | "video";

/**
 * OutputModality
 *
 * OpenAPI `OutputModality`.
 */
export type OutputModality =
    | "text"
    | "image"
    | "embeddings"
    | "audio"
    | "video"
    | "rerank"
    | "speech"
    | "transcription";

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/health";
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RefreshDataRefreshPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/refresh";
};

export type RefreshDataRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetModelsModelsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/models";
};

export type GetModelsModelsGetResponses = {
    /**
     * Response Get Models Models Get
     *
     * Successful Response
     */
    200: Array<CombinedModel>;
};

export type GetModelsModelsGetResponse =
    GetModelsModelsGetResponses[keyof GetModelsModelsGetResponses];
