// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AppMeta
 */
export type AppMeta = {
    /**
     * Enrichment Cost Usd
     *
     * Lifetime USD spent on opt-in OpenRouter/Exa web enrichment
     */
    enrichment_cost_usd: number;
    /**
     * Last Refresh At
     *
     * ISO-8601 UTC timestamp of the last successful model data refresh
     */
    last_refresh_at: string | null;
};

/**
 * CombinedModel
 */
export type CombinedModel = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name?: string;
    /**
     * Creator
     */
    creator?: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Created
     */
    created?: number | null;
    /**
     * Url Openrouter
     */
    url_openrouter?: string | null;
    /**
     * Knowledge Cutoff
     */
    knowledge_cutoff?: number | null;
    /**
     * Context Length
     */
    context_length?: number | null;
    /**
     * Input Modalities
     */
    input_modalities: Array<InputModality>;
    /**
     * Output Modalities
     */
    output_modalities: Array<OutputModality>;
    /**
     * Pricing Input
     */
    pricing_input?: number | null;
    /**
     * Pricing Output
     */
    pricing_output?: number | null;
    /**
     * Selected Provider
     */
    selected_provider?: string | null;
    /**
     * Throughput
     */
    throughput?: number | null;
    /**
     * Latency Ms
     */
    latency_ms?: number | null;
    /**
     * Benchmark Or Intelligence Index
     */
    benchmark_or_intelligence_index?: number | null;
    /**
     * Benchmark Or Coding Index
     */
    benchmark_or_coding_index?: number | null;
    /**
     * Benchmark Or Agentic Index
     */
    benchmark_or_agentic_index?: number | null;
    /**
     * Is Open Weights
     */
    is_open_weights?: boolean | null;
    /**
     * Parameters B
     */
    parameters_b?: number | null;
};

/**
 * InputModality
 *
 * OpenAPI `InputModality`.
 */
export type InputModality = 'text' | 'image' | 'file' | 'audio' | 'video';

/**
 * OutputModality
 *
 * OpenAPI `OutputModality`.
 */
export type OutputModality = 'text' | 'image' | 'embeddings' | 'audio' | 'video' | 'rerank' | 'speech' | 'transcription';

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMetaMetaGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/meta';
};

export type GetMetaMetaGetResponses = {
    /**
     * Successful Response
     */
    200: AppMeta;
};

export type GetMetaMetaGetResponse = GetMetaMetaGetResponses[keyof GetMetaMetaGetResponses];

export type GetModelsModelsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/models';
};

export type GetModelsModelsGetResponses = {
    /**
     * Response Get Models Models Get
     *
     * Successful Response
     */
    200: Array<CombinedModel>;
};

export type GetModelsModelsGetResponse = GetModelsModelsGetResponses[keyof GetModelsModelsGetResponses];
